"use strict";
let numbers = [1, 2, 3];
numbers.push(5, 4, 2);
numbers.push(3.2, 5.5555, -13);
console.log(numbers);
const nomes = ["Wagner", "Kiwi", "Márcio"];
nomes.push("Filipe");
nomes.push("A");
nomes.push("Daniel");
console.log(nomes);
